import Head from 'next/head';

const Home = () => {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className="bg-blue-50">
				<div>
					<p className="text-blue-300 text-desktop-h1">This is the first project</p>
				</div>
			</main>
		</>
	);
};

export default Home;
