import Head from 'next/head';

import ButtonAnchor from '../common/atoms/ButtonAnchor';
import ButtonBase from '../common/atoms/ButtonBase';
import ButtonLink from '../common/atoms/ButtonLink';
import Banner from '../modules/home/Banner';

const Home = () => {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className="">
				<Banner />
			</main>
		</>
	);
};

export default Home;
